# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{g_already_grid}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["C. Jason Harrelson (midas)"]
  s.date = %q{2011-08-04}
  s.description = %q{A Guilded Rails component that generates a rich grid control from an ActiveRecord.}
  s.email = %q{jason@lookforwardenterprises.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "History.txt",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "g_already_grid.gemspec",
    "lib/g_already_grid.rb",
    "lib/g_already_grid/templates/guilded.already_grid.html.erb",
    "lib/g_already_grid/view_helpers.rb",
    "lib/generators/already_grid_assets/already_grid_assets_generator.rb",
    "lib/generators/already_grid_assets/templates/default.css",
    "lib/generators/already_grid_assets/templates/gridHeadBg.gif",
    "lib/generators/already_grid_assets/templates/gridSort.gif",
    "lib/generators/already_grid_assets/templates/gridSortAsc.gif",
    "lib/generators/already_grid_assets/templates/gridSortDesc.gif",
    "lib/generators/already_grid_assets/templates/guilded.already_grid.js",
    "lib/generators/already_grid_assets/templates/guilded.already_grid.min.js",
    "lib/generators/already_grid_assets/templates/jquery-already_grid-0.1.js",
    "lib/generators/already_grid_assets/templates/jquery-already_grid-0.1.min.js",
    "rails_generators/already_grid_assets/already_grid_assets_generator.rb",
    "rails_generators/already_grid_assets/templates/default.css",
    "rails_generators/already_grid_assets/templates/gridHeadBg.gif",
    "rails_generators/already_grid_assets/templates/gridSort.gif",
    "rails_generators/already_grid_assets/templates/gridSortAsc.gif",
    "rails_generators/already_grid_assets/templates/gridSortDesc.gif",
    "rails_generators/already_grid_assets/templates/guilded.already_grid.js",
    "rails_generators/already_grid_assets/templates/guilded.already_grid.min.js",
    "rails_generators/already_grid_assets/templates/jquery-already_grid-0.1.js",
    "rails_generators/already_grid_assets/templates/jquery-already_grid-0.1.min.js",
    "script/console",
    "script/destroy",
    "script/generate",
    "spec/generators/already_grid_assets_generator_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "tasks/rspec.rake"
  ]
  s.homepage = %q{http://github.com/midas/g_already_grid}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.0}
  s.summary = %q{A Guilded Rails component that generates a rich grid control from an ActiveRecord.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<gem-dandy>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["= 1.3.2"])
      s.add_runtime_dependency(%q<rails>, [">= 2.3.10"])
      s.add_runtime_dependency(%q<guilded>, [">= 1.0"])
      s.add_runtime_dependency(%q<will_paginate>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 2.10.2"])
    else
      s.add_dependency(%q<gem-dandy>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, ["= 1.3.2"])
      s.add_dependency(%q<rails>, [">= 2.3.10"])
      s.add_dependency(%q<guilded>, [">= 1.0"])
      s.add_dependency(%q<will_paginate>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 2.10.2"])
    end
  else
    s.add_dependency(%q<gem-dandy>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, ["= 1.3.2"])
    s.add_dependency(%q<rails>, [">= 2.3.10"])
    s.add_dependency(%q<guilded>, [">= 1.0"])
    s.add_dependency(%q<will_paginate>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 2.10.2"])
  end
end

